services:
  postgres:
    container_name: postgres-game-store-app
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: game_store_app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  postgres:
    driver: local